# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08sc.proto\x12\x05proto\"!\n\x0cStartRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"2\n\rStartResponse\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\" \n\x0bStopRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"1\n\x0cStopResponse\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\" \n\x0bLogsRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"/\n\x0cLogsResponse\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0c\n\x04logs\x18\x02 \x03(\t\"\"\n\rStatusRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"3\n\x0eStatusResponse\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xdf\x01\n\x08ScPlugin\x12\x34\n\x05Start\x12\x13.proto.StartRequest\x1a\x14.proto.StartResponse\"\x00\x12\x31\n\x04Stop\x12\x12.proto.StopRequest\x1a\x13.proto.StopResponse\"\x00\x12\x31\n\x04Logs\x12\x12.proto.LogsRequest\x1a\x13.proto.LogsResponse\"\x00\x12\x37\n\x06Status\x12\x14.proto.StatusRequest\x1a\x15.proto.StatusResponse\"\x00\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_STARTREQUEST']._serialized_start=19
  _globals['_STARTREQUEST']._serialized_end=52
  _globals['_STARTRESPONSE']._serialized_start=54
  _globals['_STARTRESPONSE']._serialized_end=104
  _globals['_STOPREQUEST']._serialized_start=106
  _globals['_STOPREQUEST']._serialized_end=138
  _globals['_STOPRESPONSE']._serialized_start=140
  _globals['_STOPRESPONSE']._serialized_end=189
  _globals['_LOGSREQUEST']._serialized_start=191
  _globals['_LOGSREQUEST']._serialized_end=223
  _globals['_LOGSRESPONSE']._serialized_start=225
  _globals['_LOGSRESPONSE']._serialized_end=272
  _globals['_STATUSREQUEST']._serialized_start=274
  _globals['_STATUSREQUEST']._serialized_end=308
  _globals['_STATUSRESPONSE']._serialized_start=310
  _globals['_STATUSRESPONSE']._serialized_end=361
  _globals['_SCPLUGIN']._serialized_start=364
  _globals['_SCPLUGIN']._serialized_end=587
# @@protoc_insertion_point(module_scope)
